Repository Quesddo/Client, pull requests merged in 2025-02, with the labels that each got.

#2 chore(TODO-24): axios 커스텀 훅
  eslint.config.mjs
  src/apis/apiClient.ts
  src/hooks/useAxios.ts
Labels: 🎈 chore

#1 feat(TODO-12): 디자인시스템 구축
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-Light.woff
  public/fonts/Pretendard-Medium.woff
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-SemiBold.woff
  src/styles/fonts.css
  src/styles/globals.css
Labels: ✨ feat

#3 chore: react-hook-form 설치
  package.json
  pnpm-lock.yaml
Labels: 🎈 chore

#4 chore: tailwind 관련 라이브러리 추가 및 설정
  .prettierrc
  package.json
  pnpm-lock.yaml
  src/utils/cn.ts
Labels: 🎈 chore

#6 chore(TODO-49): 랜덤 리뷰어 지정 기능 추가
  .github/workflows/random-reviewer.yml
Labels: 🎈 chore

#7 fix: package.json 오류 수정
  package.json
Labels: 🔥 hotfix

#11 fix: 랜덤리뷰어 workflow target branch 오타 수정
  .github/workflows/random-reviewer.yml
Labels: 🔥 hotfix

#10 style(TODO-50): 반응형 breakpoint 설정
  src/styles/globals.css
Labels: 🎨 style

#16 chore(TODO-13): vercel 배포를 위한 sync 자동화 파이프라인 구축
  .github/workflows/vercel-deploy.yml
  build.sh
Labels: 🎈 chore

#17 fix(TODO-54): 디자인토큰 `text-lg`의 line-height 오타 수정 `18px => 28px`
  src/styles/globals.css
Labels: 🔥 hotfix

#15 feat(TODO-20): Button 컴포넌트, Input 컴포넌트 구현
  package.json
  src/components/atoms/Button.tsx
  src/components/atoms/Input.tsx
Labels: ✨ feat

#19 chore(TODO-53): Tanstack-Query 훅 (세팅)
  src/hooks/todo/useAddTodo.ts
  src/hooks/todo/useTodos.ts
  src/pages/_app.tsx
  src/types/todo.ts
Labels: 🎈 chore

#22 chore(TODO-53): Tanstack-Query 오타 수정
  src/pages/_app.tsx
Labels: 🎈 chore

#18 feat(TODO-39): Button 컴포넌트 disabled 스타일 수정
  src/components/atoms/Button.tsx
Labels: ⛏ fix

#26 chore(TODO-61): feature에 랜덤리뷰어 적용 및 main, dev에 기본적인 CI구축
  .github/workflows/develop-push.yml
  .github/workflows/main-pull-request.yml
  .github/workflows/main-push.yml
  .github/workflows/random-reviewer.yml
Labels: 🎈 chore

#29 chore(TODO-61): CI 파이프라인 오류 수정 및 feature/base 브랜치 CI 구축
  .github/workflows/ci.yml
  .github/workflows/develop-push.yml
  .github/workflows/main-push.yml
  .github/workflows/vercel-deploy.yml
Labels: 🎈 chore

#37 chore(TODO-69): OAS generator 도입하여 API 타입 추출
  .gitignore
  src/types/types.ts
Labels: 🎈 chore

#39 feat(TODO-72): breakpoint 수정
  src/styles/globals.css
Labels: 🎈 chore

#36 fix(TODO-20): Button 컴포넌트 스타일 오류 수정
  src/components/atoms/Button.tsx
  src/pages/_app.tsx
  src/styles/globals.css
Labels: ⛏ fix

#24 feat(TODO-55): 공통 atomic 컴포넌트 stylebook 추가
  src/components/atoms/Button.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Input.stories.ts
  src/stories/button.css
Labels: ✨ feat

#40 chore(TODO-71): [husky] staged된 변경사항만 실행되도록 수정
  .husky/commit-msg
  .husky/pre-commit
  .lintstagedrc.js
  package.json
Labels: 🎈 chore

#43 chore(TODO-73): storybook 예시 제거
  .github/workflows/merge-main-to-dev.yml
  src/components/atoms/Button.tsx
  src/pages/_app.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Input.stories.ts
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/globals.css
Labels: 🎈 chore

#45 feat(TODO-74): Dropdown 공통 컴포넌트 분리 및 범용성 개선
  src/components/atoms/dropdown/dropdown.tsx
Labels: ✨ feat

#44 feat(TODO-59): [모든 할 일 목록 페이지] 목록 리스트 부분을 아토믹으로 구현
  public/active-check.png
  public/file.png
  public/inactive-check.png
  public/link.png
  public/note-view.png
  public/note-write.png
  public/round-kebab.png
  src/components/atoms/ActionIcon.tsx
  src/components/atoms/TodoCheckbox.tsx
  src/components/atoms/TodoTitle.tsx
  src/components/molecules/TodoItem.tsx
  src/components/organisms/Modal.tsx
  src/components/organisms/TodoList.tsx
  src/hooks/todo/useCreateTodo.ts
  src/hooks/todo/useUpdateTodo.ts
  src/pages/_app.tsx
  src/pages/todo/index.tsx
Labels: ✨ feat

#41 feat(TODO-70): 모바일 헤더 추가
  public/icons/flag-goal.png
  public/icons/flag.png
  public/icons/fold.png
  public/icons/hamburger.png
  public/icons/home.png
  public/icons/logo.png
  public/icons/logo_horizontal.png
  public/icons/profile.png
  src/pages/_app.tsx
  src/views/layouts/atoms/MenuItem.tsx
  src/views/layouts/atoms/TabSideMenuItem.tsx
  src/views/layouts/molecules/TabSideMenuList.tsx
  src/views/layouts/organisms/MenuDashBoard.tsx
  src/views/layouts/organisms/MenuGoal.tsx
  src/views/layouts/organisms/Profile.tsx
  src/views/layouts/organisms/SidebarHeader.tsx
  src/views/layouts/template/Sidebar.tsx
Labels: ✨ feat

#51 refactor(TODO-78): 사이드바 리팩터링
  src/views/layouts/organisms/MenuGoal.tsx
  src/views/layouts/organisms/SidebarHeader.tsx
  src/views/layouts/template/Sidebar.tsx
Labels: ✂ refactor

#52 Feat( TODO-14): 사이드바 퍼블리싱
  README.md
  public/icons/flag-goal.png
  public/icons/flag.png
  public/icons/fold.png
  public/icons/hamburger.png
  public/icons/home.png
  public/icons/logo.png
  public/icons/logo_horizontal.png
  public/icons/profile.png
  src/pages/_app.tsx
  src/views/layouts/atoms/MenuItem.tsx
  src/views/layouts/atoms/TabSideMenuItem.tsx
  src/views/layouts/molecules/TabSideMenuList.tsx
  src/views/layouts/organisms/MenuDashBoard.tsx
  src/views/layouts/organisms/MenuGoal.tsx
  src/views/layouts/organisms/Profile.tsx
  src/views/layouts/organisms/SidebarHeader.tsx
  src/views/layouts/template/Sidebar.tsx
Labels: ✨ feat

#48 style(TODO-77): 할 일목록 리스트 컴포넌트 스타일 미세 수정
  src/components/atoms/TodoCheckbox.tsx
Labels: 🎨 style

#47 chore(TODO-75): 허스키 롤백 및 main=>dev merge 로직수정
  .github/workflows/merge-main-to-dev.yml
  .husky/pre-commit
  .lintstagedrc.js
Labels: 🎈 chore

#49 chore(TODO-76): 스토리북 배포 자동화
  .github/workflows/storybook.yml
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
Labels: 🎈 chore

#54 style(TODO-83): 사이드바 스타일 수정
  src/views/layouts/organisms/MenuDashBoard.tsx
  src/views/layouts/template/Sidebar.tsx
Labels: 🎨 style

#55 chore(TODO-84): 공통 컴포넌트 구조 변경
  src/components/atoms/action-icon/ActionIcon.tsx
  src/components/atoms/button/Button.stories.ts
  src/components/atoms/button/Button.tsx
  src/components/atoms/input/Input.stories.ts
  src/components/atoms/input/Input.tsx
  src/components/atoms/todo-checkbox/TodoCheckbox.tsx
  src/components/atoms/todo-title/TodoTitle.tsx
  src/components/molecules/todo-item/TodoItem.tsx
  src/components/organisms/modal/Modal.tsx
  src/components/organisms/todo-list/TodoList.tsx
  src/pages/todo/index.tsx
Labels: 🎈 chore

#57 chore(TODO-90): params type에 teamId 속성 제거
  src/types/types.ts
Labels: 🎈 chore

#56 style(TODO-88): sm 최소 컨텐츠 + 사이드바 오픈 일 때의 스타일 수정
  src/styles/globals.css
  src/views/layouts/template/Sidebar.tsx
Labels: 🎨 style

#53 feat(TODO-80): 목표 생성/가져오기 hooks
  src/hooks/goal/useCreateGoal.ts
  src/hooks/goal/useFetchGoals.ts
Labels: ✨ feat

#60 chore(TODO-92): 공통 컴포넌트 스타일 및 속성 수정
  src/components/atoms/button/Button.tsx
  src/components/atoms/input/Input.tsx
Labels: 🎨 style, 🎈 chore

#61 fix(TODO-102): Instance 에러 케이스 수정
  src/apis/apiClient.ts
Labels: ⛏ fix

#59 style(TODO-81): [모든 할 일 목록페이지] 페이지 스타일 및 스토리북
  public/small-blue-plus.png
  src/components/organisms/todo-list/dummy.ts
  src/components/organisms/todo-list/todoList.stories.tsx
  src/hooks/todo/useUpdateTodo.ts
  src/pages/todo/index.tsx
  src/views/todo/todoPage/Todos.tsx
Labels: 🎨 style, ✂ refactor

#62 style(TODO-103): sidebar 태블릿 환경에서 기본 close
  src/views/layouts/template/Sidebar.tsx
Labels: 🎨 style

#66 test(TODO-93): 할 일 체크토글 유닛테스트
  src/components/atoms/todo-checkbox/todoCheckbox.test.tsx
Labels: 🧪 test

#68 feat(TODO-111): PlusIcon 컴포넌트 구현
  src/components/atoms/plus-icon/PlusIcon.stories.ts
  src/components/atoms/plus-icon/PlusIcon.tsx
Labels: ✨ feat

#73 refactor(TODO-119): Card 컴포넌트 구조 세분화
  views/notes/card/card.tsx
Labels: ✂ refactor

#72 refactor(TODO-64): auth hook 추가, view 변경
  public/img_logo.png
  public/visibility_off.png
  public/visibility_on.png
  src/hooks/auth/useSign.ts
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/types/Sign.ts
  src/views/sign/Form.tsx
  src/views/sign/Input.tsx
  src/views/sign/Modal.tsx
  src/views/sign/fieldSet.ts
Labels: ✂ refactor

#76 chore(TODO-126): [CI/CD] pr시 스토리북이 모든 feature브랜치에 적용되도록 수정
  .github/workflows/storybook.yml
Labels: 🎈 chore

#82 feat(TODO-136): 날짜 포맷 변환 함수 구현
  src/utils/formatDate/formatDate.test.ts
  src/utils/formatDate/formatDate.ts
Labels: ✨ feat

#81 style(TODO-135): Sidebar 기본 open 상태 및 Button 컴포넌트 style 수정
  src/components/atoms/button/Button.tsx
  src/views/layouts/template/Sidebar.tsx
Labels: 🎨 style

#80 feat(TODO-114): 목표 무한 스크롤 구현
  package.json
  pnpm-lock.yaml
  src/hooks/goal/useCreateGoal.ts
  src/hooks/goal/useIniniteGoals.ts
  src/views/layouts/molecules/GoalCreationForm.tsx
  src/views/layouts/molecules/TabSideMenuList.tsx
  src/views/layouts/organisms/MenuGoal.tsx
Labels: ✨ feat

#84 feat(TODO-141): 사이드바를 노출하지 않는 경로 추가
  src/pages/_app.tsx
Labels: ✨ feat

#85 feat(TODO-137): 생성, 수정 폼 InputModal 컴파운드 구성
  public/icons/active-check-white.png
  public/icons/inactive-check.png
  public/icons/uploaded.png
  src/components/atoms/close-icon/CloseIcon.tsx
  src/components/atoms/input/Input.tsx
  src/components/organisms/modal/CreateModal.tsx
  src/components/organisms/modal/InputModal.tsx
  src/components/organisms/todo-list/TodoList.tsx
  src/contexts/InputModalContext.tsx
  src/hooks/useDragAndDrop.ts
  src/hooks/useFilePreview.ts
  src/pages/_app.tsx
  src/pages/todo/index.tsx
  src/styles/globals.css
  src/styles/modal.css
Labels: ✨ feat

#83 feat(TODO-66): 로그인/회원가입 유효성 체크 기능 구현
  src/hooks/auth/useSign.ts
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/types/Sign.ts
  src/views/sign/Form.tsx
  src/views/sign/Input.stories.tsx
  src/views/sign/Input.tsx
  src/views/sign/LoginPage.stories.tsx
  src/views/sign/Modal.stories.tsx
  src/views/sign/SignupPage.stories.tsx
  src/views/sign/fieldSet.ts
Labels: ✨ feat

#88 style(TODO-135): Sidebar 기본 open 상태 및 Button 컴포넌트 style 수정
  src/components/atoms/button/Button.tsx
  src/views/layouts/template/Sidebar.tsx
Labels: 🎨 style

#91 feat(TODO-32): 노트 작성 마크업 및 react-hook-form 적용
  public/icons/check.png
  public/icons/delete.png
  src/components/atoms/page-title/PageTitle.tsx
  src/pages/_app.tsx
  src/views/layouts/template/Sidebar.tsx
  src/views/note-creation-form/Editor.tsx
  src/views/note-creation-form/InputWithCount.tsx
  src/views/note-creation-form/NoteCreationForm.tsx
  src/views/note-creation-form/Toast.tsx
  src/views/note-creation-form/ToastBtn.tsx
Labels: ✨ feat

#89 refactor(TODO-140): [Dropdown] 리팩토링 - 외부 클릭, 애니메이션
  src/components/atoms/action-dropdown/ActionDropdown.stories.tsx
  src/components/atoms/action-dropdown/ActionDropdown.tsx
  src/components/atoms/action-icon/ActionIcon.tsx
  src/components/atoms/dropdown/dropdown.stories.tsx
  src/components/atoms/dropdown/dropdown.tsx
  views/notes/card/card.tsx
Labels: ✂ refactor

#90 feat(TODO-144): PageTItle 컴포넌트 추가 및 sidebar 내부에서 pathname에 따라 hidden 결정
  src/components/atoms/page-title/PageTitle.stories.ts
  src/components/atoms/page-title/PageTitle.tsx
  src/pages/_app.tsx
  src/views/layouts/template/Sidebar.tsx
Labels: ✨ feat

#93 feat(TODO-151): [노트 상세보기] 공통컴포넌트 분리
  public/icons/delete.png
  public/icons/flag-goal-lg.png
  public/icons/flag-goal-sm.png
  src/components/atoms/divider/Divider.stories.tsx
  src/components/atoms/divider/Divider.tsx
  src/components/atoms/exit-btn/ExitBtn.stories.tsx
  src/components/atoms/exit-btn/ExitBtn.tsx
  src/components/atoms/goal-item/GoalItem.stories.tsx
  src/components/atoms/goal-item/GoalItem.tsx
  src/components/atoms/todo-chip/TodoChip.stories.tsx
  src/components/atoms/todo-chip/TodoChip.tsx
Labels: ✨ feat

#99 feat(TODO-156): [Spinner] 컴포넌트 구현
  public/icons/spinner.gif
  src/components/atoms/spinner/Spinner.stories.tsx
  src/components/atoms/spinner/Spinner.tsx
Labels: ✨ feat

#96 style(TODO-154): button 태그에 `cursor-pointer` 스타일 추가
  src/styles/globals.css
Labels: 🎨 style

#95 feat(TODO-149): Toaster 컴포넌트 구현
  public/icons/check.png
  public/icons/error.png
  src/components/organisms/toaster/Toast.stories.tsx
  src/components/organisms/toaster/Toast.test.tsx
  src/components/organisms/toaster/Toast.tsx
  src/components/organisms/toaster/ToastProvider.tsx
  src/components/organisms/toaster/Toaster.tsx
  src/hooks/useToast.ts
  src/pages/_app.tsx
  src/styles/globals.css
  src/styles/toast.css
Labels: ✨ feat

#100 feat(TODO-155): react-quill-new 라이브러리 설치 및 적용
  package.json
  pnpm-lock.yaml
  src/views/note-creation-form/Editor.tsx
Labels: ✨ feat

#102 chore(TODO-158): MSW 라이브러리 설치 및 스토리북에 초기설정
  .storybook/preview.ts
  .storybook/preview.tsx
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/mocks/handlers.ts
Labels: 🎈 chore

#97 feat(TODO-63): 로그인/회원가입 페이지 구현
  public/img_logo.png
  public/visibility_off.png
  public/visibility_on.png
  src/apis/apiClient.ts
  src/apis/apiRefreshTokens.ts
  src/components/AuthGuard.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useSign.ts
  src/pages/_app.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/types/Sign.ts
  src/utils/tokenUtils.ts
  src/views/sign/Form.tsx
  src/views/sign/Input.stories.tsx
  src/views/sign/Input.tsx
  src/views/sign/LoginPage.stories.tsx
  src/views/sign/Modal.stories.tsx
  src/views/sign/Modal.tsx
  src/views/sign/SignPage.stories.tsx
  src/views/sign/SignupPage.stories.tsx
  src/views/sign/fieldSet.ts
Labels: ✨ feat

#106 feat(TODO-23): 모든 할 일 목록 페이지
  src/components/organisms/todo-list/todoList.stories.tsx
  src/hooks/todo/useUpdateTodo.ts
  src/mocks/handlers.ts
  src/mocks/todo/todoHandlers.ts
  src/mocks/todo/todoMockData.ts
  src/pages/todo/index.tsx
  src/views/todo/TodoPage.stories.tsx
  src/views/todo/todo-checkbox/todoCheckbox.test.tsx
  src/views/todo/todoPage/Todos.tsx
Labels: ✨ feat

#110 feat(TODO-133): [사이드바] 레이아웃 수정 및 홈, 대시보드 경로 이동 처리
  public/icons/logo-horizontal.png
  src/pages/_app.tsx
  src/views/layouts/organisms/MenuDashBoard.tsx
  src/views/layouts/organisms/SidebarHeader.tsx
  src/views/layouts/template/Sidebar.stories.tsx
  src/views/layouts/template/Sidebar.tsx
Labels: ✨ feat

#109 style(TODO-165): 대시보드 기본 레이아웃
  public/icons/flag-box.png
  public/icons/progress.png
  public/icons/todo-recently.png
  src/components/atoms/title-with-icon/TitleWithIcon.tsx.tsx
  src/pages/dashboard/index.tsx
  src/views/dashboard/goal-based-todo/GoalBasedTodo.tsx
  src/views/dashboard/my-progress/MyProgress.tsx
  src/views/dashboard/recent-todo/RecentTodo.tsx
Labels: 🎨 style

#108 feat(TODO-163): 노트 작성 URL query에 따른 사이드바 적용 및 임시저장, 링크 모달 연결
  public/icons/delete-circle-gray.png
  public/icons/delete_circle.png
  public/icons/embed.png
  src/apis/noteApi.ts
  src/components/atoms/button/Button.stories.ts
  src/components/atoms/button/Button.tsx
  src/hooks/note/useCreateNote.ts
  src/hooks/note/useNoteDraft.ts
  src/hooks/note/useUpdateNote.ts
  src/pages/_app.tsx
  src/views/note-creation-form/Editor.tsx
  src/views/note-creation-form/NoteCreationForm.tsx
  src/views/note-creation-form/Toast.tsx
  src/views/note-creation-form/ToastBtn.tsx
  src/views/note/note-drawer/NoteDrawer.tsx
  src/views/note/note-form/Editor.tsx
  src/views/note/note-form/EditorTextCounter.tsx
  src/views/note/note-form/LinkDisplay.tsx
  src/views/note/note-form/LinkModal.tsx
  src/views/note/note-form/NoteCreationForm.tsx
  src/views/note/note-form/NoteForm.tsx
  src/views/note/note-form/NoteUpdateForm.tsx
  src/views/note/note-form/TitleCounter.tsx
  src/views/note/note-form/ToastBtn.tsx
  src/views/note/note-form/utils/noteStorage.ts
Labels: ✨ feat

#112 chore(TODO-169): [스토리북] 전역 autodocs 옵션 제거
  .storybook/preview.tsx
  src/components/atoms/action-dropdown/ActionDropdown.stories.tsx
  src/components/atoms/divider/Divider.stories.tsx
  src/components/atoms/exit-btn/ExitBtn.stories.tsx
  src/components/atoms/goal-item/GoalItem.stories.tsx
  src/components/atoms/page-title/PageTitle.stories.ts
  src/components/atoms/plus-icon/PlusIcon.stories.ts
  src/components/atoms/spinner/Spinner.stories.tsx
  src/components/atoms/todo-chip/TodoChip.stories.tsx
Labels: 🎈 chore

#111 feat(TODO-157): 목표 상세 페이지 구현
  public/icons/frame.svg
  public/icons/ic_arrow_right.svg
  public/icons/link_alt.svg
  public/icons/meatballs_menu.svg
  public/icons/note.svg
  public/icons/uploaded.svg
  src/components/atoms/progress-bar/ProgressBar.stories.tsx
  src/components/atoms/progress-bar/ProgressBar.tsx
  src/hooks/goal/useDeleteGoal.ts
  src/hooks/goal/useFetchGoal.ts
  src/hooks/goal/useUpdateGoal.ts
  src/hooks/todo/useProgressTodo.ts
  src/hooks/todo/useTodos.ts
  src/pages/goal/[goalId]/index.tsx
  src/views/goal/component/GoalSection.tsx
  src/views/goal/component/Modal.tsx
  src/views/goal/component/NoteSection.tsx
  src/views/goal/component/ProgressContainer.tsx
  src/views/goal/component/Section.tsx
  src/views/goal/component/TodoListSection.tsx
  src/views/goal/publish/goalPage.stories.tsx
  src/views/goal/publish/goalPage.tsx
Labels: ✨ feat

#116 feat(TODO-129): [노트상세보기] 사이드바 구현
  public/icons/embed.png
  src/apis/note/fetchNoteDetail.ts
  src/components/organisms/note-detail/NoteDetail.stories.tsx
  src/components/organisms/note-detail/NoteDetail.tsx
  src/components/organisms/note-detail/components/EmbeddedContent.tsx
  src/components/organisms/note-detail/components/LinkItem.tsx
  src/components/organisms/note-detail/components/NoteDetailContent.tsx
  src/mocks/handlers.ts
  src/mocks/note/noteHandlers.ts
  src/mocks/note/noteMockData.ts
  src/pages/_app.tsx
  src/types/types.ts
  src/utils/formatDate/formatDate.ts
Labels: ✨ feat

#119 feat(TODO-162): [대시보드] 초안
  public/icons/flag-box.png
  public/icons/goal.png
  public/icons/progress.png
  public/icons/todo-recently.png
  src/components/atoms/action-dropdown/ActionDropdown.tsx
  src/components/atoms/title-with-icon/TitleWithIcon.tsx.tsx
  src/components/organisms/todo-list/TodoList.tsx
  src/hooks/useTodoListAction.tsx
  src/pages/dashboard/index.tsx
  src/views/dashboard/DashboardPage.stories.tsx
  src/views/dashboard/goal-based-todo/GoalBasedTodo.tsx
  src/views/dashboard/my-progress/MyProgress.tsx
  src/views/dashboard/recent-todo/RecentTodo.tsx
  src/views/todo/todo-item/TodoItem.tsx
  src/views/todo/todo-item/action-icon/ActionIcon.tsx
Labels: ✨ feat

#120 chore(TODO-173): [사이드바] 폴더 구조 변경
  src/pages/_app.tsx
  src/views/layouts/sidebar/Sidebar.stories.tsx
  src/views/layouts/sidebar/Sidebar.tsx
  src/views/layouts/sidebar/components/AddButton.tsx
  src/views/layouts/sidebar/components/MenuDashBoard.tsx
  src/views/layouts/sidebar/components/MenuItem.tsx
  src/views/layouts/sidebar/components/Profile.tsx
  src/views/layouts/sidebar/components/SidebarHeader.tsx
  src/views/layouts/sidebar/components/goals/GoalCreationForm.tsx
  src/views/layouts/sidebar/components/goals/MenuGoal.tsx
  src/views/layouts/sidebar/components/goals/TabSideMenuItem.tsx
  src/views/layouts/sidebar/components/goals/TabSideMenuList.tsx
  src/views/todo/TodoForm.tsx
Labels: ✨ feat

#121 Revert "chore(TODO-173): [사이드바] 폴더 구조 변경"
  src/pages/_app.tsx
  src/views/layouts/atoms/MenuItem.tsx
  src/views/layouts/atoms/TabSideMenuItem.tsx
  src/views/layouts/molecules/TabSideMenuList.tsx
  src/views/layouts/organisms/MenuDashBoard.tsx
  src/views/layouts/organisms/MenuGoal.tsx
  src/views/layouts/organisms/Profile.tsx
  src/views/layouts/organisms/SidebarHeader.tsx
  src/views/layouts/sidebar/components/AddButton.tsx
  src/views/layouts/sidebar/components/goals/GoalCreationForm.tsx
  src/views/layouts/template/Sidebar.stories.tsx
  src/views/layouts/template/Sidebar.tsx
  src/views/todo/TodoForm.tsx
Labels: 🏹 revert

#122 Revert "feat(TODO-129): [노트상세보기] 사이드바 구현"
  public/icons/embed.png
  src/apis/note/fetchNoteDetail.ts
  src/components/organisms/note-detail/NoteDetail.stories.tsx
  src/components/organisms/note-detail/NoteDetail.tsx
  src/components/organisms/note-detail/components/EmbeddedContent.tsx
  src/components/organisms/note-detail/components/LinkItem.tsx
  src/components/organisms/note-detail/components/NoteDetailContent.tsx
  src/mocks/handlers.ts
  src/mocks/note/noteHandlers.ts
  src/mocks/note/noteMockData.ts
  src/pages/_app.tsx
  src/types/types.ts
  src/utils/formatDate/formatDate.ts
Labels: 🏹 revert

#124 feat(TODO-174): 로그인 페이지 이동 기능변경
  src/hooks/auth/useSign.ts
Labels: ✨ feat

#125 feat(TODO-175): 할 일 목록 기능 빈데이터 디버깅
  src/pages/todo/index.tsx
  src/views/dashboard/recent-todo/RecentTodo.tsx
  src/views/todo/todo-item/TodoItem.tsx
Labels: ⛏ fix

#128 feat(TODO-79): [사이드바] 목표 api 연동 및 링크 이동 추가
  pnpm-lock.yaml
  src/hooks/goal/useCreateGoal.ts
  src/hooks/goal/useIniniteGoals.ts
  src/hooks/user/useFetchUser.ts
  src/pages/_app.tsx
  src/views/layouts/sidebar/Sidebar.stories.tsx
  src/views/layouts/sidebar/Sidebar.tsx
  src/views/layouts/sidebar/components/MenuDashBoard.tsx
  src/views/layouts/sidebar/components/MenuItem.tsx
  src/views/layouts/sidebar/components/Profile.tsx
  src/views/layouts/sidebar/components/goals/MenuGoal.tsx
  src/views/layouts/sidebar/components/goals/TabSideMenuItem.tsx
  src/views/layouts/sidebar/components/goals/TabSideMenuList.tsx
Labels: ✨ feat

#130 feat(TODO-178): 로그아웃 기능 추가
  src/views/layouts/sidebar/components/Profile.tsx
Labels: ✨ feat
