Repository Quesddo/Client, pull requests merged in 2025-03, with the labels that each got.

#133 feat(TODO-186): [할 일 페이지] 무한스크롤
  src/components/organisms/todo-list/TodoList.tsx
  src/hooks/todo/useInfiniteTodo.ts
  src/pages/todo/index.tsx
  src/styles/globals.css
  src/styles/slideUp.css
  src/views/dashboard/recent-todo/RecentTodo.tsx
  src/views/todo/todo-item/TodoItem.tsx
  src/views/todo/todoPage/Todos.tsx
Labels: ✨ feat

#134 feat(TODO-182): 목표 상세 페이지 오류 수정
  src/contexts/GoalDetailContext.tsx
  src/hooks/todo/useTodos.ts
  src/pages/goal/[goalId]/index.tsx
  src/views/goal/component/GoalSection.tsx
  src/views/goal/component/NoteSection.tsx
  src/views/goal/component/ProgressContainer.tsx
  src/views/goal/component/TodoListSection.tsx
  src/views/goal/publish/goalPage.stories.tsx
  src/views/goal/publish/goalPage.tsx
Labels: ⛏ fix

#138 chore(TODO-190): 로그인/회원가입 큰 로고로 변경
  public/img_logo.png
Labels: 🎈 chore

#135 chore(TODO-172): [스토리북] main 기반 스토리북 배포 및 환경변수 적용
  .github/workflows/storybook.yml
  src/apis/apiClient.ts
  src/constants/env.ts
  src/mocks/note/noteHandlers.ts
  src/mocks/todo/todoHandlers.ts
Labels: 🎈 chore

#137 refactor(TODO-188): 인증레이어 로직 수정, 스피너 적용
  src/components/AuthGuard.tsx
  src/components/AuthLayer.tsx
  src/pages/_app.tsx
Labels: ✂ refactor

#140 fix(TODO-191): 할 일 목록 - 노트 사이드바 오픈 시 pathname 추가
  src/components/organisms/todo-list/TodoList.tsx
  src/views/todo/todo-item/TodoItem.tsx
  src/views/todo/todo-item/action-icon/ActionIcon.tsx
Labels: ⛏ fix, ✂ refactor

#139 fix(TODO-195): [할 일 목록 페이지] 무한스크롤 쿼리키 수정
  src/hooks/todo/useCreateTodo.ts
  src/hooks/todo/useDeleteTodo.ts
  src/hooks/todo/useInfiniteTodo.ts
  src/hooks/todo/useUpdateTodo.ts
  src/hooks/useTodoListAction.tsx
  src/pages/todo/index.tsx
  src/views/todo/todo-create-form/TodoCreateForm.tsx
  src/views/todo/todo-update-form/TodoUpdateForm.tsx
  src/views/todo/todoPage/Todos.tsx
Labels: ⛏ fix, 🚨 urgent

#144 fix(TODO-193): [CI/CD] 프로젝트 및 스토리북 배포 버그 해결
  .github/workflows/storybook.yml
  .github/workflows/vercel-deploy.yml
  build.sh
Labels: ⛏ fix, 🚨 urgent

#141 style(TODO-196): 할 일 목록 관련 스타일 수정 (아이콘 추가, 터치환경에 호버효과 제거)
  src/components/organisms/todo-list/TodoList.tsx
  src/components/organisms/todo-list/todoList.stories.tsx
  src/views/dashboard/recent-todo/RecentTodo.tsx
  src/views/todo/todo-checkbox/TodoCheckbox.tsx
  src/views/todo/todo-item/TodoItem.tsx
  src/views/todo/todo-item/action-icon/ActionIcon.tsx
Labels: 🎨 style

#143 feat(TODO-194): 에러바운더리 기능 추가
  src/components/atoms/skeleton/Skeleton.stories.tsx
  src/components/atoms/skeleton/Skeleton.tsx
  src/components/organisms/boundary-wrapper/BoundaryWrapper.tsx
  src/styles/globals.css
  src/styles/skeleton.css
Labels: ✨ feat, 🎨 style

#142 feat(TODO-189): [노트 작성/수정] 쿼리키 적용 및 에러, 로딩 리팩토링
  src/apis/noteApi.ts
  src/hooks/note/useCreateNote.ts
  src/hooks/note/useNoteDraft.ts
  src/hooks/note/useUpdateNote.ts
  src/views/note/note-drawer/NoteDrawer.tsx
  src/views/note/note-form/NoteCreationForm.tsx
  src/views/note/note-form/NoteUpdateForm.tsx
Labels: ✂ refactor

#145 style(TODO-202): 로그인/회원가입 스타일 & 기타
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/views/sign/SignForm.tsx
Labels: 🎨 style, 🎈 chore

#151 feat(TODO-201): [노트 작성/수정] 노트 작성/수정 일부 workflow 수정
  src/views/note/note-form/Editor.tsx
  src/views/note/note-form/EditorTextCounter.tsx
  src/views/note/note-form/NoteForm.tsx
  src/views/note/note-form/NoteUpdateForm.tsx
  src/views/note/note-form/TitleCounter.tsx
Labels: ✨ feat

#148 fix(TODO-198): [노트 무한스크롤] 초기 cursor가 0으로 들어가는 버그 수정
  src/apis/note/fetchNotes.ts
  src/hooks/note/useInfiniteNotes.ts
Labels: ⛏ fix

#150 refactor(TODO-207): 할 일 목록페이지 BoundaryWrapper 적용
  src/components/organisms/todo-list/todoList.stories.tsx
  src/hooks/goal/useFetchGoals.ts
  src/mocks/todo/todoMockData.ts
  src/pages/todo/index.tsx
  src/views/todo/TodoForm.tsx
  src/views/todo/todo-item/TodoItem.tsx
  src/views/todo/todo-item/todoItem.stories.tsx
Labels: ✂ refactor

#152 fix(TODO-204): 목표 상세 페이지 목표를 수정/삭제 시 사이드바와 맞지 않는 부분 수정
  src/hooks/goal/useDeleteGoal.ts
  src/hooks/goal/useUpdateGoal.ts
  src/pages/goal/[goalId]/index.tsx
  src/views/goal/component/GoalHeader.tsx
  src/views/goal/component/GoalSection.tsx
  src/views/goal/component/NoteSection.tsx
  src/views/goal/component/Section.tsx
  src/views/goal/component/TodoListSection.tsx
Labels: ⛏ fix, 🎨 style, 🎈 chore

#153 feat(TODO-210): [노트 상세] 노트 내용에 editor 라이브러리 적용
  src/components/organisms/note-detail/components/NoteDetailContent.tsx
  src/views/note/editor/ReactQuillEditor.tsx
  src/views/note/note-form/Editor.tsx
Labels: ✨ feat

#154 style(TODO-211): 로그인/회원가입 레이아웃 수정
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/views/sign/Main.tsx
  src/views/sign/SignForm.tsx
Labels: 🎨 style

#157 chore(TODO-214): [라이브러리 설치] Tanstack Query Devtools 설치
  package.json
  pnpm-lock.yaml
  src/pages/_app.tsx
Labels: 🎈 chore

#156 feat(TODO-215): [useTodos] 완료 여부에 따라 할 일 필터링하여 받아오도록 확장
  src/apis/todoApi.ts
  src/hooks/todo/useTodos.ts
  src/types/todo.ts
Labels: ✨ feat

#159 feat(TODO-208): [노트 작성/수정] 임시저장 workflow 개선
  src/hooks/note/useAutoSaveNoteDraft.ts
  src/hooks/note/useNoteDraft.ts
  src/hooks/note/useNoteStorage.ts
  src/views/note/editor/ReactQuillEditor.tsx
  src/views/note/note-drawer/NoteDrawer.tsx
  src/views/note/note-form/DraftNoteReminderToast.tsx
  src/views/note/note-form/Editor.tsx
  src/views/note/note-form/LinkModal.tsx
  src/views/note/note-form/NoteCreationForm.tsx
  src/views/note/note-form/NoteForm.tsx
  src/views/note/note-form/NoteUpdateForm.tsx
  src/views/note/note-form/TitleWithCounter.tsx
  src/views/note/note-form/ToastBtn.tsx
  src/views/note/note-form/utils/noteStorage.ts
Labels: ✨ feat, ✂ refactor

#161 chore(TODO-222): [노트 모아보기] interface 대문자로 수정, 컴포넌트 key값 부여
  src/apis/note/fetchNotes.ts
  src/views/notes/note-list/NoteList.tsx
Labels: 🎈 chore

#163 feat(TODO-216): [대시보드/목표별 할 일] 프로그래스바, 자세히보기 기능 구현
  src/hooks/todo/useProgressTodo.ts
  src/views/dashboard/goal-based-todo/GoalBasedTodo.tsx
  src/views/dashboard/goal-based-todo/components/ProgressBar.tsx
Labels: ✨ feat

#167 feat(TODO-228): 중복된 목표 무한 스크롤 api hooks 처리
  src/apis/goalApi.ts
  src/hooks/goal/useFetchGoals.ts
  src/hooks/goal/useInfiniteGoals.ts
  src/hooks/goal/useSidebarInfiniteGoals.ts
  src/views/layouts/sidebar/components/goals/TabSideMenuList.tsx
  src/views/todo/TodoForm.tsx
Labels: ✂ refactor, 🚨 urgent

#166 refactor(TODO-224): [할 일 수정폼] useEffect에서 상태설정 - 개선 시도
  src/views/todo/todo-update-form/TodoUpdateForm.tsx
Labels: ✂ refactor

#168 refactor(TODO-229): inputModal 폼 타입 설정
  src/components/organisms/todo-list/TodoList.tsx
  src/contexts/InputModalContext.tsx
  src/pages/dashboard/index.tsx
  src/pages/todo/index.tsx
  src/views/dashboard/goal-based-todo/GoalBasedTodo.tsx
  src/views/goal/todo/GoalTodoContainer.tsx
  src/views/layouts/sidebar/components/MenuDashBoard.tsx
  src/views/note/note-form/Editor.tsx
  src/views/todo/TodoForm.stories.tsx
Labels: ⛏ fix, ✂ refactor

#164 feat(TODO-220): 목표상세 무한스크롤 기능
  src/contexts/GoalDetailContext.tsx
  src/hooks/goal/useDeleteGoal.ts
  src/hooks/todo/useInfiniteTodo.ts
  src/pages/goal/[goalId]/index.tsx
  src/views/goal/header/Progress.tsx
  src/views/goal/todo/GoalDoneList.tsx
  src/views/goal/todo/GoalTodoContainer.tsx
  src/views/goal/todo/GoalTodoList.tsx
Labels: ✨ feat, 🎨 style, ✂ refactor

#165 feat(TODO-221): [노트 작성/수정] 링크 임베드 추가
  src/pages/api/check-iframe.ts
  src/views/note/editor/ReactQuillEditor.tsx
  src/views/note/embed/LinkEmbed.tsx
  src/views/note/note-drawer/NoteDrawer.tsx
  src/views/note/note-form/DraftNoteReminderToast.tsx
  src/views/note/note-form/LinkDisplay.tsx
  src/views/note/note-form/NoteForm.tsx
Labels: ✨ feat

#170 refactor(TODO-231): [useInfiniteGoals] 필요한 파트마다 쿼리키 개별적으로 관리하도록 수정
  src/apis/goalApi.ts
  src/hooks/goal/useInfiniteGoals.ts
  src/hooks/goal/useSidebarInfiniteGoals.ts
  src/views/todo/TodoForm.tsx
Labels: ✂ refactor

#169 refactor(TODO-213): 목표 상세에서 할 일 생성 시 기존 목표 세팅
  src/apis/fileApi.ts
  src/hooks/todo/form/useTodoForm.ts
  src/views/goal/todo/GoalTodoContainer.tsx
  src/views/goal/todo/GoalTodoList.tsx
  src/views/todo/todo-create-form/TodoCreateForm.tsx
  src/views/todo/todo-update-form/TodoUpdateForm.tsx
Labels: ✂ refactor

#171 feat(TODO-217): [대시보드/목표별 할 일] 목표 무한스크롤 구현
  src/views/dashboard/goal-based-todo/GoalBasedTodo.tsx
  src/views/dashboard/goal-based-todo/components/GoalItem.tsx
  src/views/dashboard/goal-based-todo/goal-based-todo.md
Labels: ✨ feat

#173 hotfix(TODO-233): 인증레이어 수정, 위치 변경
  src/hocs/AuthLayer.tsx
  src/pages/_app.tsx
Labels: 🔥 hotfix, 🚨 urgent

#172 feat(TODO-227): 모바일 사이드바 링크 클릭 시 닫힘 처리 및 SMD 크기부터 열림 고정
  src/views/layouts/sidebar/Sidebar.stories.tsx
  src/views/layouts/sidebar/Sidebar.tsx
  src/views/layouts/sidebar/components/CloseSidebarLink.tsx
  src/views/layouts/sidebar/components/MenuDashBoard.tsx
  src/views/layouts/sidebar/components/SidebarHeader.tsx
  src/views/layouts/sidebar/components/goals/TabSideMenuItem.tsx
Labels: ✨ feat

#176 feat(TODO-234): [노트 작성/수정] 기능 고도화(유효성 검사, 페이지 이동 안내 팝업, 임베드)
  src/hooks/note/useBlockNavigation.tsx
  src/pages/api/check-iframe.ts
  src/views/note/editor/ReactQuillEditor.tsx
  src/views/note/embed/LinkEmbed.tsx
  src/views/note/note-drawer/NoteDrawer.tsx
  src/views/note/note-form/LinkDisplay.tsx
  src/views/note/note-form/LinkModal.tsx
  src/views/note/note-form/NoteCreationForm.tsx
  src/views/note/note-form/NoteForm.tsx
  src/views/note/note-form/NoteUpdateForm.tsx
  src/views/note/note-form/TitleWithCounter.tsx
Labels: ✨ feat

#174 feat(TODO-209): 대시보드 진행상황 추가
  package.json
  pnpm-lock.yaml
  src/hooks/todo/useProgressTodo.ts
  src/styles/gauge.css
  src/styles/globals.css
  src/views/dashboard/my-progress/MyProgress.tsx
  src/views/dashboard/my-progress/components/Gauge.tsx
Labels: ✨ feat, 🎨 style, 🎈 chore

#175 refactor(TODO-236): 로그인/회원가입 리렌더링 이슈
  src/hooks/auth/useSign.ts
  src/views/sign/Input.stories.tsx
  src/views/sign/SignForm.tsx
  src/views/sign/SignInput.tsx
  src/views/sign/SignPage.stories.tsx
Labels: ✂ refactor

#177 chore(TODO-232): [노트모아보기, 목표상세] SMD 사이즈에서 사이드바에 가려지는 문제 해결
  src/components/organisms/note-detail/NoteDetail.tsx
  src/pages/goal/[goalId]/index.tsx
  src/pages/goal/[goalId]/notes/index.tsx
Labels: 🎈 chore

#178 feat(TODO-237): 할일 폼 목표리스트 무한스크롤, title 공백 유효성
  src/components/organisms/modal/InputModal.tsx
  src/views/todo/input-dropdown/InputDropdown.tsx
  src/views/todo/todo-create-form/TodoCreateForm.tsx
  src/views/todo/todo-form/TodoForm.stories.tsx
  src/views/todo/todo-form/TodoForm.tsx
  src/views/todo/todo-form/ValidateMassage.tsx
  src/views/todo/todo-update-form/TodoUpdateForm.tsx
Labels: ✨ feat

#179 chore(TODO-239): 스토리북 컨벤션에 맞춰 수정
  src/components/atoms/action-dropdown/ActionDropdown.stories.tsx
  src/components/atoms/button/Button.stories.ts
  src/components/atoms/divider/Divider.stories.tsx
  src/components/atoms/exit-btn/ExitBtn.stories.tsx
  src/components/atoms/goal-item/GoalItem.stories.tsx
  src/components/atoms/input/Input.stories.ts
  src/components/atoms/page-title/PageTitle.stories.ts
  src/components/atoms/plus-icon/PlusIcon.stories.ts
  src/components/atoms/progress-bar/ProgressBar.stories.tsx
  src/components/atoms/skeleton/Skeleton.stories.tsx
  src/components/atoms/spinner/Spinner.stories.tsx
  src/components/atoms/todo-chip/TodoChip.stories.tsx
  src/components/molecules/error-fallback/ErrorFallback.stories.tsx
  src/components/organisms/toaster/Toast.stories.tsx
  src/components/organisms/todo-list/todoList.stories.tsx
  src/views/sign/LoginPage.stories.tsx
  src/views/sign/SignPage.stories.tsx
  src/views/sign/SignupPage.stories.tsx
Labels: 🎈 chore

#181 refactor(TODO-240): hooks 관련 및 노트 수정 컴포넌트 컨벤션에 따라 수정
  src/hooks/goal/useSidebarInfiniteGoals.ts
  src/hooks/note/useAutoSaveNoteDraft.ts
  src/hooks/note/useBlockNavigation.ts
  src/hooks/note/useCreateNote.ts
  src/hooks/note/useNoteStorage.ts
  src/hooks/note/useUpdateNote.ts
  src/hooks/todo/form/useTodoForm.ts
  src/hooks/useToast.ts
  src/views/layouts/sidebar/components/goals/TabSideMenuList.tsx
  src/views/note/note-drawer/NoteDrawer.tsx
  src/views/note/note-form/DraftNoteReminderToast.tsx
  src/views/note/note-form/LinkModal.tsx
  src/views/note/note-form/NoteCreateForm.tsx
  src/views/note/note-form/NoteForm.tsx
  src/views/note/note-form/NoteUpdateForm.tsx
Labels: ✂ refactor, 🎈 chore

#182 chore(TODO-238): 파비콘 수정
  public/favicon.ico
Labels: 🎈 chore

#183 chore(TODO-224): [목표상세] 배경 밖으로 컨텐츠 튀어나오는 부분 수정
  src/pages/goal/[goalId]/index.tsx
Labels: 🎈 chore

#184 style(TODO-246): [노트 상세] 레이아웃, 링크 스타일 수정
  src/views/note/note-detail/NoteDetail.tsx
  src/views/note/note-detail/components/LinkItem.tsx
  src/views/note/note-detail/components/NoteDetailContent.tsx
Labels: 🎨 style

#188 style(TODO-245): 함수 컨벤션 및 할일폼 스타일
  src/components/organisms/modal/InputModal.tsx
  src/hooks/todo/useTodoListAction.ts
  src/hooks/useFilePreview.ts
  src/pages/dashboard/index.tsx
  src/pages/todo/index.tsx
  src/views/todo/input-dropdown/InputDropdown.tsx
Labels: 🎨 style

#187 style(TODO-248): 대시보드 진행상황 스타일링 1차수정
  src/styles/gauge.css
  src/views/dashboard/my-progress/MyProgress.tsx
  src/views/dashboard/my-progress/components/Gauge.tsx
Labels: 🎨 style

#186 refactor(TODO-243): [사이드바] 목표, 프로필 리팩토링
  src/hooks/goal/useSidebarInfiniteGoals.ts
  src/views/layouts/sidebar/Sidebar.tsx
  src/views/layouts/sidebar/components/goals/MenuGoal.tsx
  src/views/layouts/sidebar/components/goals/TabSideMenuList.tsx
Labels: ✂ refactor

#190 fix(TODO-249): [목표 생성] 낙관적 업데이트 제거 후 비관적 업데이트 적용
  src/hooks/goal/useCreateGoal.ts
  src/views/layouts/sidebar/components/goals/TabSideMenuList.tsx
Labels: ⛏ fix

#191 style(TODO-251): 적용되지 않았던 텍스트 스타일 지정 및 _app.tsx main 태그 수정
  src/components/molecules/error-fallback/ErrorFallback.tsx
  src/pages/_app.tsx
  src/views/note/note-form/GoalTodoDisplay.tsx
Labels: 🎨 style

#189 feat(TODO-247): title 로직 오류 수정 및 SEO 최적화 메타 태그 추가
  public/icons/logo-lg.png
  public/images/thumb.png
  src/components/atoms/quesddo-head/QuesddoHead.tsx
Labels: ✨ feat

#192 style(TODO-250): 목표상세 팝업 스타일 수정
  src/views/goal/component/Modal.tsx
  src/views/goal/header/GoalTitle.tsx
Labels: 🎨 style

#193 fix(TODO-252): [사이드바, 노트 작성/수정] 할 일 생성 모달 및 링크 업로드 모달 생성 조건문 추가
  src/views/layouts/sidebar/components/MenuDashBoard.tsx
  src/views/note/note-form/LinkModal.tsx
Labels: ⛏ fix

#194 style(TODO-253): 회원가입 완료 후 모달 스타일 변경
  src/components/molecules/popup/Popup.tsx
  src/views/sign/Modal.tsx
  src/views/sign/SignForm.tsx
Labels: 🎨 style

#195 fix(TODO-255): 사이드바 목표 무한 스크롤 오류 처리
  src/views/layouts/sidebar/components/goals/TabSideMenuList.tsx
Labels: ⛏ fix

#198 refactor(TODO-219): 대시보드 - 최근 등록한 할 일 최적화 및 useTodo 매개변수 개선
  src/hooks/todo/useTodos.ts
  src/views/dashboard/goal-based-todo/components/TodoWrapper.tsx
  src/views/dashboard/recent-todo/RecentTodo.tsx
Labels: ✂ refactor

#196 refactor(TODO-223): 할일 요청 todoApi 정리
  src/apis/todoApi.ts
  src/hooks/todo/useCreateTodo.ts
  src/hooks/todo/useDeleteTodo.ts
  src/hooks/todo/useProgressTodo.ts
  src/hooks/todo/useTodos.ts
  src/hooks/todo/useUpdateTodo.ts
  src/views/note/note-form/NoteCreateForm.tsx
  src/views/todo/todo-update-form/TodoUpdateForm.tsx
Labels: ✂ refactor

#197 fix(TODO-256): [노트 수정/작성] 작성 중 페이지 이동 오류 처리
  src/hooks/note/useBlockNavigation.ts
  src/views/note/note-drawer/NoteDrawer.tsx
  src/views/note/note-form/NoteForm.tsx
Labels: ⛏ fix

#199 refactor(TODO-192): `fetchNote` API 함수 통합 및 `useFetchNote` 훅 분리
  src/apis/noteApi.ts
  src/hooks/note/useFetchNote.ts
  src/pages/_app.tsx
  src/views/note/note-detail/components/EmbeddedContent.tsx
  src/views/note/note-detail/components/LinkItem.tsx
  src/views/note/note-detail/components/NoteDetailContent.tsx
  src/views/note/note-form/NoteUpdateForm.tsx
Labels: ✂ refactor

#200 fix(TODO-258): 할일폼 목표드롭다운 무한스크롤 제거
  src/components/organisms/modal/InputModal.tsx
  src/views/todo/input-dropdown/InputDropdown.tsx
  src/views/todo/input-dropdown/InputDropdownItem.tsx
  src/views/todo/todo-form/TodoForm.tsx
Labels: ⛏ fix

#201 refactor(TODO-235): [쿼리 키 구조화] 쿼리 키 팩토리 적용
  package.json
  pnpm-lock.yaml
  src/apis/todoApi.ts
  src/hooks/auth/useSign.ts
  src/hooks/goal/useCreateGoal.ts
  src/hooks/goal/useDeleteGoal.ts
  src/hooks/goal/useFetchGoal.ts
  src/hooks/goal/useInfiniteGoals.ts
  src/hooks/goal/useUpdateGoal.ts
  src/hooks/note/useCreateNote.ts
  src/hooks/note/useDeleteNote.ts
  src/hooks/note/useFetchNote.ts
  src/hooks/note/useInfiniteNotes.ts
  src/hooks/note/useUpdateNote.ts
  src/hooks/todo/useCreateTodo.ts
  src/hooks/todo/useDeleteTodo.ts
  src/hooks/todo/useInfiniteTodo.ts
  src/hooks/todo/useProgressTodo.ts
  src/hooks/todo/useTodos.ts
  src/hooks/todo/useUpdateTodo.ts
  src/hooks/user/useFetchUser.ts
  src/pages/dashboard/index.tsx
  src/query-keys/goalQueryKeys.ts
  src/query-keys/index.ts
  src/query-keys/noteQueryKeys.ts
  src/query-keys/query-keys.md
  src/query-keys/todoQueryKeys.ts
  src/query-keys/userQueryKeys.ts
  src/views/note/note-form/NoteCreateForm.tsx
  src/views/todo/todo-update-form/TodoUpdateForm.tsx
Labels: ✂ refactor

#202 refactor(TODO-257): 할일폼 모달 전역관리 방식으로 변경
  src/components/organisms/todo-list/TodoList.tsx
  src/components/organisms/todo-list/todoList.stories.tsx
  src/contexts/TodoListActionContext.tsx
  src/pages/_app.tsx
  src/pages/dashboard/index.tsx
  src/pages/todo/index.tsx
  src/views/dashboard/goal-based-todo/GoalBasedTodo.tsx
  src/views/dashboard/goal-based-todo/components/GoalItem.tsx
  src/views/dashboard/goal-based-todo/components/TodoWrapper.tsx
  src/views/dashboard/recent-todo/RecentTodo.tsx
  src/views/goal/todo/GoalDoneList.tsx
  src/views/goal/todo/GoalTodoContainer.tsx
  src/views/goal/todo/GoalTodoList.tsx
  src/views/layouts/sidebar/components/MenuDashBoard.tsx
  src/views/todo/todo-create-form/TodoCreateForm.tsx
  src/views/todo/todo-drawer/TodoDrawer.tsx
  src/views/todo/todo-item/TodoItem.tsx
  src/views/todo/todo-item/action-icon/ActionIcon.tsx
  src/views/todo/todoPage/Todos.tsx
Labels: ✂ refactor

#204 refactor(TODO-261): [노트] 작성/수정 구조 리팩토링 및 쿼리키 구조화 적용
  src/hooks/todo/useFetchTodo.ts
  src/pages/_app.tsx
  src/views/note/note-drawer/NoteDrawer.tsx
  src/views/note/note-form/GoalTodoDisplay.tsx
  src/views/note/note-form/NoteCreateForm.tsx
  src/views/note/note-form/NoteForm.tsx
  src/views/note/note-form/NoteUpdateForm.tsx
Labels: ✂ refactor

#205 style(TODO-254): 할일폼 목표드롭다운 목표 없을 때
  src/views/todo/input-dropdown/InputDropdown.tsx
Labels: 🎨 style

#206 style(TODO-263): [할일 목록페이지] 스피너 위치 조정 및 스토리북 부활
  src/pages/todo/index.tsx
  src/views/dashboard/goal-based-todo/GoalBasedTodo.tsx
  src/views/dashboard/my-progress/MyProgress.tsx
  src/views/dashboard/recent-todo/RecentTodo.tsx
  src/views/todo/todoPage/TodoPage.stories.tsx
  src/views/todo/todoPage/Todos.tsx
Labels: 🎨 style

#208 hotfix(TODO-265): 에러바운더리 재시도 안되는 이슈
  src/components/organisms/boundary-wrapper/BoundaryWrapper.tsx
Labels: 🔥 hotfix

#207 feat(TODO-262): [노트 작성/수정] 폴더 구조 변경 및 스토리북 작성
  src/mocks/note/noteHandlers.ts
  src/mocks/todo/todoHandlers.ts
  src/mocks/todo/todoMockData.ts
  src/views/note/note-create-form/NoteCreateForm.stories.tsx
  src/views/note/note-create-form/NoteCreateForm.tsx
  src/views/note/note-detail/components/NoteDetailContent.tsx
  src/views/note/note-drawer/NoteDrawer.tsx
  src/views/note/note-form/NoteForm.tsx
  src/views/note/note-form/components/DraftNoteReminderToast.tsx
  src/views/note/note-form/components/Editor.tsx
  src/views/note/note-form/components/EditorTextCounter.tsx
  src/views/note/note-form/components/GoalTodoDisplay.tsx
  src/views/note/note-form/components/LinkDisplay.tsx
  src/views/note/note-form/components/LinkModal.tsx
  src/views/note/note-form/components/TitleWithCounter.tsx
  src/views/note/note-update-form/NoteUpdateForm.stories.tsx
  src/views/note/note-update-form/NoteUpdateForm.tsx
  src/views/note/react-quill-editor/ReactQuillEditor.tsx
Labels: ✨ feat, 🎈 chore

#210 fix(TODO-268): 느린 인터넷 환경에서 로그인 된 사용자가 루트 접속 시 빈화면 보이는 현상 처리
  src/pages/dashboard/index.tsx
  src/views/dashboard/recent-todo/RecentTodo.tsx
Labels: 🔥 hotfix, 🚨 urgent

#213 refactor(TODO-241): 페이지 및 API 경로 하드코딩 제거 및 중앙 관리 적용
  src/apis/apiRefreshTokens.ts
  src/apis/fileApi.ts
  src/apis/goalApi.ts
  src/apis/noteApi.ts
  src/apis/signApi.ts
  src/apis/todoApi.ts
  src/hooks/goal/useDeleteGoal.ts
  src/hooks/todo/useInfiniteTodo.ts
  src/hooks/user/useFetchUser.ts
  src/pages/404.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/router/apiRoutes.ts
  src/router/pageRoutes.ts
  src/views/dashboard/goal-based-todo/components/GoalItem.tsx
  src/views/dashboard/recent-todo/RecentTodo.tsx
  src/views/goal/note/GoalNote.tsx
  src/views/layouts/AuthGuard.tsx
  src/views/layouts/sidebar/components/MenuDashBoard.tsx
  src/views/layouts/sidebar/components/Profile.tsx
  src/views/layouts/sidebar/components/SidebarHeader.tsx
  src/views/note/note-create-form/NoteCreateForm.tsx
  src/views/note/note-update-form/NoteUpdateForm.tsx
  src/views/notes/card/Card.tsx
  src/views/sign/SignForm.tsx
  src/views/todo/todo-item/action-icon/ActionIcon.tsx
Labels: ✂ refactor

#209 feat(TODO-267): [노트 작성/수정] 임시 저장 및 페이지 이동 예외 처리
  src/hooks/note/useAutoSaveNoteDraft.ts
  src/hooks/note/useBlockNavigation.ts
  src/views/note/note-form/NoteForm.tsx
  src/views/note/note-form/components/Editor.tsx
  src/views/note/note-form/components/EditorTextCounter.tsx
  src/views/note/note-form/utils/checkEmptyNote.ts
Labels: ✨ feat, ✂ refactor

#212 fix(TODO-269): 로그인 탭 화면 전환 시 값 사라짐
  src/hooks/user/useFetchUser.ts
Labels: ⛏ fix

#211 refactor(TODO-260): 목표상세 타이틀 부분 리펙터링
  src/apis/goalApi.ts
  src/hooks/goal/useDeleteGoal.ts
  src/hooks/goal/useFetchGoal.ts
  src/hooks/goal/useUpdateGoal.ts
  src/views/goal/component/GoalPopup.tsx
  src/views/goal/component/Modal.tsx
  src/views/goal/header/GoalTitle.tsx
  src/views/goal/header/GoalTitleActionDropdown.tsx
  src/views/goal/header/GoalTitleModals.tsx
  src/views/sign/SignPage.stories.tsx
Labels: 🎨 style, ✂ refactor

#215 style(TODO-273): [노트 모아보기] 카드 hover시 shadow 적용
  src/views/notes/card/Card.tsx
Labels: 🎨 style

#214 feat(TODO-180): [노트 상세] 임베드 거부된 사이트 예외처리
  src/apis/canEmbedApi.ts
  src/hooks/note/useCanEmbed.ts
  src/pages/api/check-iframe.tsx
  src/query-keys/embedQueryKeys.ts
  src/query-keys/index.ts
  src/query-keys/query-keys.md
  src/views/note/note-detail/components/EmbeddedContent.tsx
Labels: ✨ feat

#216 style(TODO-277): Toaster 스타일 수정
  src/components/organisms/toaster/Toaster.tsx
  src/views/layouts/sidebar/Sidebar.tsx
Labels: 🎨 style

#217 refactor(TODO-275): [노트 작성] 노트 작성 시도가 있었던 경우 페이지 이동 시 모달 open
  src/hooks/note/useAutoSaveNoteDraft.ts
  src/views/note/note-create-form/NoteCreateForm.tsx
  src/views/note/note-form/NoteForm.tsx
  src/views/note/note-form/utils/checkEmptyNote.ts
Labels: ✂ refactor

#219 refactor(TODO-278): 할일 목록 드롭다운 분리, useEffect 제거
  src/views/todo/todo-item/action-dropdown/TodoActionDropdown.tsx
  src/views/todo/todo-item/action-icon/ActionIcon.tsx
Labels: ✂ refactor

#221 style(TODO-279): [대시보드] 최근 할 일 로딩 레이아웃 위치 수정
  src/pages/dashboard/index.tsx
  src/views/dashboard/recent-todo/RecentTodo.tsx
Labels: 🎨 style, 🚨 urgent

#222 style(TODO-271): [노트상세] 수정, 삭제 버튼 디자인 변경
  src/views/note/note-detail/NoteDetail.tsx
  src/views/note/note-detail/components/ActionBtns.tsx
Labels: 🎨 style

#223 refactor(TODO-281): [노트 작성/수정] 자동 임시 저장 로직 리팩토링
  src/hooks/note/useAutoSaveNoteDraft.ts
Labels: ✂ refactor

#224 style(TODO-282): [전체 레이아웃] 모바일 레이아웃에 맞춰 수정 및 목표 입력 스타일 수정
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/views/layouts/sidebar/components/goals/GoalCreationForm.tsx
Labels: 🎨 style

#227 chore(TODO-284) codecov 워크플로우 세팅
  .github/workflows/codecov.yml
Labels: 🧪 test

#225 docs(TODO-283): 리드미에 페이지별 영상 추가
  README.md
Labels: 📃 docs

#230 docs(TODO-283) 리드미 수정
  README.md
Labels: 📃 docs

#233 test(TODO-280): 공통컴포넌트 테스트코드 작성
  src/components/atoms/page-title/PageTitle.test.tsx
  src/components/atoms/plus-icon/PlusIcon.test.tsx
  src/components/atoms/plus-icon/__snapshots__/PlusIcon.test.tsx.snap
  src/components/atoms/progress-bar/ProgressBar.tsx
  src/components/atoms/todo-chip/TodoChip.test.tsx
  src/components/molecules/popup/Popup.test.tsx
  src/components/molecules/popup/Popup.tsx
Labels: 🧪 test
